/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SFFLRegistryRollup } from "./SFFLRegistryRollup";
export * as factories from "./factories";
export { SFFLRegistryRollup__factory } from "./factories/SFFLRegistryRollup__factory";
