version: "3"

networks:
  near-sffl-relayer-rs:
    driver: bridge

services:
  # relayer_431614_rs:
  #   build:
  #     context: ../../relayer-rs
  #     dockerfile: Dockerfile
  #   container_name: near-sffl-relayer-rs-421614
  #   volumes:
  #     - ${NEAR_KEYS_DIR}:/root/.near-credentials
  #   networks:
  #     - near-sffl-relayer-rs
  #   expose:
  #     - 9093
  #   command:
  #     - run-args
  #     - --rpc-url
  #     - wss://arbitrum-sepolia-rpc.publicnode.com
  #     - --da-account-id
  #     - sfrelayer431614-2.testnet
  #     - --key-path
  #     - /root/.near-credentials/${NEAR_CHAIN_ID}/sfrelayer431614-2.testnet.json
  #     - --network
  #     - ${NEAR_RPC_URL}
  #     - --metrics-ip-port-address
  #     - near-sffl-relayer-rs-431614:9093
  #   restart: unless-stopped
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "1g"
  #       max-file: "20"
  #       compress: "true"

  relayer_11155420_rs:
    build:
      context: ../../relayer-rs
      dockerfile: Dockerfile
    container_name: near-sffl-relayer-rs-21155420
    volumes:
      - ${NEAR_KEYS_DIR}:/root/.near-credentials
    networks:
      - near-sffl-relayer-rs
    expose:
      - 9094
    command:
      - run-args
      - --rpc-url
      - wss://optimism-sepolia-rpc.publicnode.com
      - --da-account-id
      - sfrelayer21155420-2.testnet
      - --key-path
      - /root/.near-credentials/${NEAR_CHAIN_ID}/sfrelayer21155420-2.testnet.json
      - --network
      - ${NEAR_RPC_URL}
      - --metrics-ip-port-address
      - near-sffl-relayer-rs-21155420:9094
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        max-file: "20"
        compress: "true"

  grafana:
    profiles: ["monitoring"]
    image: grafana/grafana:9.4.1
    container_name: grafana-rs
    volumes:
      - grafana_data_relayer_rs:/var/lib/grafana
      - ../../grafana/provisioning:/etc/grafana/provisioning
    networks:
      - near-sffl-relayer-rs
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - "127.0.0.1:3002:3000"

  prometheus:
    profiles: ["monitoring"]
    image: prom/prometheus:v2.42.0
    container_name: prometheus-rs
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data_relayer_rs:/prometheus
    networks:
      - near-sffl-relayer-rs
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
      - --web.enable-remote-write-receiver
    restart: unless-stopped
    ports:
      - "127.0.0.1:9092:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  prometheus_data_relayer_rs:
  grafana_data_relayer_rs: