global:
  scrape_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: "docker-host-alpha"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "sffl-operator0"
    scrape_interval: 5s
    static_configs:
      - targets: ["nffl-operator0:9090"]
        labels:
          role: "operator"
          instance: "0"

  - job_name: "sffl-operator1"
    scrape_interval: 5s
    static_configs:
      # host.docker.internal might not work on linux
      # TODO: do https://stackoverflow.com/a/67158212/4971151
      # - targets: ["host.docker.internal:9090"]
      - targets: ["nffl-operator1:9091"]
        labels:
          role: "operator"
          instance: "1"

  - job_name: "sffl-aggregator"
    scrape_interval: 5s
    static_configs:
      - targets: ["nffl-aggregator:9091"]

  - job_name: "sffl-indexer"
    scrape_interval: 5s
    static_configs:
      - targets: ["nffl-indexer:9090"]

    relabel_configs:
      # is this actually useful? We already have the job name