[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read-write", path = "script/output/17000"},
    { access = "read-write", path = "script/output/31337"},
    { access = "read-write", path = "script/output/421614"},
    { access = "read-write", path = "script/output/11155420"}
]

# solc_version = "0.8.12"
auto_detect_solc = true

# This is a low optimizer_runs setting since the `RegistryCoordinator`
# contract size is really high and we must extend it in SFFL. It would be
# important to increase this value in the future, especially in a mainnet
# deployment.
optimizer = true
optimizer_runs = 100

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default.dvn]
path = "src/dvn"
solc_version = "0.8.20"

