{
 "title": "Aggregator",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "operatorId",
    "query": {
     "query": "label_values(sffl_aggregator_last_message_received_time, operator_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Last Checkpoints",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sffl_aggregator_last_checkpoint_reference_sent",
     "legendFormat": "Sent"
    },
    {
     "expr": "sffl_aggregator_last_checkpoint_task_reference_received",
     "legendFormat": "Received"
    },
    {
     "expr": "sffl_aggregator_last_checkpoint_task_reference_aggregated",
     "legendFormat": "Aggregated"
    }
   ]
  },
  {
   "title": "Last Operator Set Updates",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sffl_aggregator_last_operator_set_update_received",
     "legendFormat": "Received"
    },
    {
     "expr": "sffl_aggregator_last_operator_set_update_aggregated",
     "legendFormat": "Aggregated"
    }
   ]
  },
  {
   "title": "Last State Root Updates",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sffl_aggregator_last_state_root_update_received",
     "legendFormat": "Received (#{{rollup_id}})"
    },
    {
     "expr": "sffl_aggregator_last_state_root_update_aggregated",
     "legendFormat": "Aggregated (#{{rollup_id}})"
    }
   ]
  },
  {
   "title": "Initializations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sffl_aggregator_reinitializations_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors and Expirations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 4 },
   "targets": [
    {
     "expr": "sffl_aggregator_errored_submissions_total",
     "legendFormat": "Errored Submissions"
    },
    {
     "expr": "sffl_aggregator_api_errors_total",
     "legendFormat": "API Errors"
    },
    {
     "expr": "sffl_aggregator_expired_tasks_total",
     "legendFormat": "Expired Tasks"
    },
    {
     "expr": "sffl_aggregator_expired_messages_total",
     "legendFormat": "Expired Messages"
    },
    {}
   ]
  },
  {
   "title": "API Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 4 },
   "targets": [
    {
     "expr": "sffl_aggregator_checkpoint_messages_requests_total",
     "legendFormat": "Checkpoint Messages"
    },
    {
     "expr": "sffl_aggregator_operator_set_update_requests_total",
     "legendFormat": "Operator Set Update"
    },
    {
     "expr": "sffl_aggregator_state_root_update_requests_total",
     "legendFormat": "State Root Update"
    }
   ]
  },
  { "title": "Operator Metrics - $operatorId", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }, "repeat": "operatorId" },
  {
   "title": "Last Received Message Times",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sffl_aggregator_last_message_received_time{operator_id=\"$operatorId\"}",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  {
   "title": "Operator Signing",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 13 },
   "targets": [
    {
     "expr": "sffl_aggregator_signed_checkpoint_task_responses_total{operator_id=\"$operatorId\"}",
     "legendFormat": "Checkpoint"
    },
    {
     "expr": "sffl_aggregator_signed_operator_set_update_messages_total{operator_id=\"$operatorId\"}",
     "legendFormat": "Operator Set Update (errored: {{errored}})"
    },
    {
     "expr": "sffl_aggregator_signed_state_root_update_messages_total{operator_id=\"$operatorId\"}",
     "legendFormat": "State Root Update (rollup_id: {{rollup_id}}, errored: {{errored}}, near_da: {{has_near_da}})"
    }
   ]
  }
 ]
}