{
 "title": "Operator",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "rollupId",
    "query": {
     "query": "label_values(sffl_operator_last_block_received, rollup_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Operator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Initializations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sffl_operator_initialization_count",
     "legendFormat": "Initializations"
    }
   ]
  },
  {
   "title": "Last Checkpoint and Operator Set Update Submission IDs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sffl_operator_last_checkpoint_id_responded",
     "legendFormat": "Checkpoint"
    },
    {
     "expr": "sffl_operator_last_operator_set_update_id_responded",
     "legendFormat": "Operator Set Update"
    }
   ]
  },
  {
   "title": "Checkpoint and Operator Set Update Submissions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sffl_operator_checkpoint_task_response_submissions{resend=\"false\"}",
     "legendFormat": "Checkpoint"
    },
    {
     "expr": "sffl_operator_operator_set_update_submissions{resend=\"false\"}",
     "legendFormat": "Operator Set Update"
    }
   ]
  },
  {
   "title": "Checkpoint and Operator Set Update Resubmissions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 12 },
   "targets": [
    {
     "expr": "sffl_operator_checkpoint_task_response_submissions{resend=\"true\"}",
     "legendFormat": "Checkpoint"
    },
    {
     "expr": "sffl_operator_operator_set_update_submissions{resend=\"true\"}",
     "legendFormat": "Operator Set Update"
    }
   ]
  },
  {
   "title": "MQ Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sffl_operator_consumer_num_of_mq_arrivals",
     "legendFormat": "MQ Arrivals"
    }
   ]
  },
  {
   "title": "Resend Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 20 },
   "targets": [
    {
     "expr": "sffl_operator_resend_queue_size",
     "legendFormat": "Resend Queue Size"
    }
   ]
  },
  {
   "title": "Performance Score",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 28 },
   "targets": [
    { "expr": "eigen_performance_score", "legendFormat": "Performance Score" }
   ]
  },
  {
   "title": "Registered Stakes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 28 },
   "targets": [
    { "expr": "eigen_registered_stakes", "legendFormat": "Quorum {{quorum_number}}" }
   ]
  },
  {
   "title": "Rollup Metrics (Chain ID $rollupId)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "repeat": "rollupId"
  },
  {
   "title": "Initial Block Number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sffl_operator_initialization_initial_block_number{rollup_id=\"$rollupId\"}",
     "legendFormat": "Chain ID {{rollup_id}}"
    }
   ]
  },
  {
   "title": "Blocks Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sffl_operator_last_block_received{rollup_id=\"$rollupId\"}",
     "legendFormat": "Last Block Received"
    }
   ]
  },
  {
   "title": "Block Timestamps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 38 },
   "targets": [
    {
     "expr": "sffl_operator_last_block_received_timestamp{rollup_id=\"$rollupId\"}",
     "legendFormat": "Block Timestamp"
    }
   ]
  },
  {
   "title": "State Root Update Submissions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sffl_operator_state_root_update_submissions{rollup_id=\"$rollupId\", resend=\"false\"}",
     "legendFormat": "State Root Update Submissions"
    }
   ]
  },
  {
   "title": "State Root Update Resubmissions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sffl_operator_state_root_update_submissions{rollup_id=\"$rollupId\", resend=\"true\"}",
     "legendFormat": "State Root Update Resubmissions"
    }
   ]
  },
  {
   "title": "Missed MQ Blocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sffl_operator_attestor_num_of_missed_mq_blocks{rollup_id=\"$rollupId\"}",
     "legendFormat": "Missed MQ Blocks"
    }
   ]
  },
  {
   "title": "Mismatched Blocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 59 },
   "targets": [
    {
     "expr": "sffl_operator_consumer_num_of_mismatched_blocks{rollup_id=\"$rollupId\"}",
     "legendFormat": "Mismatched Blocks"
    }
   ]
  },
  { "title": "NEAR DA Indexer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "MQ Block Batches Publishing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "sffl_indexer_rabbit_publisher_num_of_published_blocks",
     "legendFormat": "Successful Publishes"
    },
    {
     "expr": "sffl_indexer_rabbit_publisher_num_failed_published",
     "legendFormat": "Failed Publishes"
    }
   ]
  },
  {
   "title": "NEAR DA Candidates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 99 },
   "targets": [
    {
     "expr": "sffl_indexer_candidates_validator_num_of_successful_candidates",
     "legendFormat": "Successful Candidates"
    },
    {
     "expr": "sffl_indexer_candidates_validator_num_of_failed_candidates",
     "legendFormat": "Failed Candidates"
    },
    {
     "expr": "sffl_indexer_block_listener_num_of_candidates",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}