{
 "title": "SFFL",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "New Tasks Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sffl_num_tasks_received", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Signed Tasks Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sffl_num_signed_task_responses_accepted_by_aggregator",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Performance Score",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "eigen_performance_score{avs_name=\"super-fast-finality-layer\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}