name: contracts-forge-tests

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'bindings/**'
      - 'contracts/**'

jobs:
  Test:
    name: Contracts Forge Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install npm dependencies
        run: npm ci
        working-directory: ./contracts/evm

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install forge dependencies
        run: forge install
        working-directory: ./contracts/evm

      - name: Run tests
        run: forge test -vvv --no-match-contract FFI
        working-directory: ./contracts/evm
