name: Test deployment

on:
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  test-deploy:
    name: Test docs deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
            node-version: 18
            cache: npm
            cache-dependency-path: docs

      - name: Install dependencies
        run: npm ci 
        working-directory: docs
      - name: Test build website
        run: npm run build
        working-directory: docs
