
name: integration-tests

on:
  push:
    branches:
      - main
  pull_request:


jobs:  
  Test:
    name: Integration Test
    runs-on: ubuntu-latest
    timeout-minutes: 70

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build indexer container
        uses: docker/build-push-action@v5
        with:
          load: true
          context: .
          file: ./indexer/Dockerfile
          tags: nffl-indexer
          cache-from: type=gha,scope=indexer
          cache-to: type=gha,mode=max,scope=indexer

      - name: Build relayer container
        uses: docker/build-push-action@v5
        with:
          load: true
          context: .
          file: ./relayer/cmd/Dockerfile
          tags: nffl-test-relayer
          cache-from: type=gha,scope=relayer
          cache-to: type=gha,mode=max,scope=relayer

      - name: Build plugin container
        uses: docker/build-push-action@v5
        with:
          load: true
          context: .
          file: ./plugin/cmd/Dockerfile
          tags: nffl-operator-plugin
          cache-from: type=gha,scope=plugin
          cache-to: type=gha,mode=max,scope=plugin

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install npm dependencies
        run: npm ci
        working-directory: ./contracts/evm
        
      - name: Install near-cli
        run: npm i -g near-cli@3.5.0

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install forge dependencies
        run: forge install
        working-directory: ./contracts/evm

      - name: Go Integration Test
        run: make tests-integration

      - name: Rust Fastnear Integration Test
        run: cargo test --features it_tests
        working-directory: ./indexer

      - name: Rust Integration Test
        run: cargo test --features it-tests
        working-directory: ./tests/e2e/e2e_tests

